sudo: required
language: generic

services:
  - docker

before_install:
  - docker build  -f Dockerfile.dev -t shaneyboy/react-frontend-dev .

script:
  - docker run -e CI=true shaneyboy/react-frontend-dev yarn run test

# safelist
branches:
  only:
  - main

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  # access_key_id:
  #   secure: $AWS_ACCESS_KEY
  # secret_access_key:
  #   secure: $AWS_SECRET_KEY
  app: "getting-started-app"
  env: "Getting-started-app-env"
  bucket_name: "elasticbeanstalk-eu-west-1-992382540430"
  on:
    branch: main