sudo: required
language: generic

services:
  - docker

before_install:
  - docker build  -f Dockerfile.dev -t shaneyboy/react-frontend-dev .

script:
  - docker run -e CI=true shaneyboy/react-frontend-dev npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY"
  region: "eu-west-1"
  secret_access_key: "$AWS_SECRET_KEY"
  # access_key_id:
  #   secure: $AWS_ACCESS_KEY
  # secret_access_key:
  #   secure: $AWS_SECRET_KEY
  app: "dkr-rct"
  env: "Dkr-rct-env"
  bucket_name: "elasticbeanstalk-eu-west-1-992382540430"
  on:
    branch: main