#This is for AWS
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'

    

    # develop:
    #   watch:
    #     - action: sync
    #       path: .
    #       target: .


    # Access shell
    #docker run -it image_name sh

    # Test Sé
    #docker exec -it <CONTAINER_ID> npm run test 