version: '3'
services: 
  web: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - '5001:3000'
    # env_file:
    #   - environments/dev.env
    volumes:
      # - /usr/app/package-lock.json
      - .:/usr/app
      # - /usr/app/node_modules/
    command: 
      - npm
      - run
      - start-docker

    

    # develop:
    #   watch:
    #     - action: sync
    #       path: .
    #       target: .


    # Access shell
    #docker run -it image_name sh

    # Test Sé
    #docker exec -it <CONTAINER_ID> npm run test 